server:
  servlet:
    context-path: /api/home
  port: 8060

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tesis
    username: admin
    password: EL1p8)AsTiL7)RDx
  jpa:
    show-sql: true
    database: mysql
